language: python
python: 3.4
sudo: false
env:
  - TOXENV=py27-django111
  - TOXENV=py34-django111
  - TOXENV=docs
  - TOXENV=lint
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35-django111
install:
  - pip install tox
script:
  - tox -e $TOXENV
