language: python
python: 3.4
sudo: false
env:
  - TOXENV=py27-django111
  - TOXENV=py34-django111
  - TOXENV=py34-django20
  - TOXENV=docs
  - TOXENV=lint
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35-django111
  - python: 3.5
    env: TOXENV=py35-django20
  - python: 3.5
    env: TOXENV=py35-django21
  - python: 3.5
    env: TOXENV=py35-django22
  - python: 3.6
    env: TOXENV=py36-django111
  - python: 3.6
    env: TOXENV=py36-django20
  - python: 3.6
    env: TOXENV=py36-django21
  - python: 3.6
    env: TOXENV=py36-django22
install:
  - pip install tox
script:
  - tox -e $TOXENV
